name: Hangfire

# For Windows environment
# highlighter: rouge

# For other environments (Linux, OS X, etc.)
pygments: true
markdown: redcarpet

kramdown:
  input: GFM

github_repo: https://github.com/HangfireIO/HangfireIO.github.io
github_branch: master

paginate: 5
paginate_path: "blog/page:num/"

disqus_short_name: odinserjnet
disqus_show_comment_count: true