name: Hangfire
url: http://hangfire.io

author:
  name: 'odinserj'
  url:  https://twitter.com/odinserj

kramdown:
  auto_ids: true
  input:    GFM

highlighter: rouge

github_repo:   https://github.com/HangfireIO/HangfireIO.github.io
github_branch: master

paginate:      5
paginate_path: "blog/page:num/"

disqus_short_name:         hangfire
disqus_show_comment_count: true