name: Hangfire
title: Hangfire Blog
url: http://hangfire.io

author:
  name: 'odinserj'
  url:  https://twitter.com/odinserj

# Windows environments
# highlighter: rouge

kramdown:
  auto_ids: true
  input:    GFM

github_repo:   https://github.com/HangfireIO/HangfireIO.github.io
github_branch: master

paginate:      5
paginate_path: "blog/page:num/"

disqus_short_name:         hangfire
disqus_show_comment_count: true