name: HangFire
markdown: redcarpet
pygments: true

navigation:
- text: Quick Start
  url: http://docs.hangfire.io/en/latest/quickstart.html
- text: Features
  url: http://docs.hangfire.io/en/latest/features.html
- text: Tutorial
  url: http://docs.hangfire.io/en/latest/tutorials/index.html
- text: Packages
  url: https://www.nuget.org/packages?q=HangFire
- text: Fork me on GitHub
  url: https://github.com/odinserj/HangFire

kramdown:
  input: GFM